### ISSUE TITLE
HowTo install npm, mongo or other pipeline dependencies?

### ISSUE THREAD

**Issue by cloudscape-germany** [alvistack/docker-bamboo#1]
Hi how would you install npm, node or other dependencies you need for your pipeline?

**Comment by hswong3i** [comment]
Maybe running with docker in docker?

As I remember now bamboo support running test with docker image, shall we default install with docker-ce, then user could mount the host’s docker socket to bamboo instance, so bamboo could run whatever additional docker instance for its test?

**Comment by hswong3i** [comment]
@nottinhill most likely it is now answered by master (c133ecfdfb7774db420c1ab3f6c23d825bd562d5), please check the [README.md](https://github.com/alvistack/docker-bamboo/blob/c133ecfdfb7774db420c1ab3f6c23d825bd562d5/README.md) for more information ;-)
